### ISSUE TITLE
clarification on "not needed anymore" and garbage collection

### ISSUE THREAD

**Issue by mheiber** [tc39/proposal-symbols-as-weakmap-keys#2]
The README is really clear!

Re:

> Boxes will not keep objects indefinitely in memory. When a box is not needed anymore, the attached object can be let go.

Does "a box is not needed anymore" mean the same thing as "a box is inaccessible"?

Is this sentence saying the same thing as "when the box is garbage-collected, the attached object can be garbage-collected as well"?

If so, we might want to tweak the semantics so that the boxed object is eligible for collection when the object and its box are inaccessible. 

```js
const obj = { hello: "world" };
const box = Box(obj);
window.leakObj = obj; // the box can be collected, but the object itself must live on
```

**Comment by littledan** [comment]
Hopefully the language about garbage collection has been clarified now; please file another issue if there's anything additional to clear up.
