### ISSUE TITLE
"deref" does not fit with "box"

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-symbols-as-weakmap-keys#9]
I deref a weak ref or a pointer; i don't deref a box. I open a box, i take things out of a box, i unbox things.

**Comment by littledan** [comment]
So, would you call this method `Box.prototype.unbox`?

**Comment by ljharb** [comment]
That seems like a perfect name.

**Comment by littledan** [comment]
This proposal has moved to the direction of Symbols as WeakMap keys, so I'm closing this issue.
